#!/bin/bash 
 
block_device="${1}"

printf "Running DiskPrep using block_device=%s\n" "${block_device}"

#Mount root
cryptsetup open "${block_device}"2 cryptroot
mount /dev/mapper/cryptroot /mnt

#Mount boot
mkdir -p /mnt/boot
mount "${block_device}"1 /mnt/boot

#TODO update and verify /etc/pacman.d/mirrorlist

#Install the base packages
pacstrap /mnt base base-devel grub sudo wget vim dialog netctl wpa_supplicant dhcpcd

#Generate an fstab file
genfstab -U /mnt >> /mnt/etc/fstab

cp ./Chroot /mnt
arch-chroot /mnt ./Chroot "${block_device}"
rm /mnt/Chroot

#Unmount boot
umount /mnt/boot
rmdir /mnt/boot

#Unmount root
umount /mnt
cryptsetup close cryptroot

printf "BaseInstall finished...\n\n\n"