#!/bin/bash 
 
block_device="${1}"

printf "Running DiskPrep using block_device=%s\n" "${block_device}"

#Mount root
eval "cryptsetup open ${block_device}2 cryptroot"
eval "mount /dev/mapper/cryptroot /mnt"

#Mount boot
eval "mkdir -p /mnt/boot"
eval "mount ${block_device}1 /mnt/boot"

#TODO update and verify /etc/pacman.d/mirrorlist

#Install the base packages
eval "pacstrap /mnt base base-devel grub sudo wget vim"

#Generate an fstab file
eval "genfstab -U /mnt >> /mnt/etc/fstab"

eval "cp ./Chroot /mnt"
eval "arch-chroot /mnt ./Chroot ${block_device}"
eval "rm /mnt/Chroot"

#Unmount boot
eval "umount /mnt/boot"
eval "rmdir /mnt/boot"

#Unmount root
eval "umount /mnt"
eval "cryptsetup close cryptroot"

printf "BaseInstall finished...\n\n\n"