#!/bin/bash 
 
block_device="${1}"

 function myEval { 
    #TODO - look into not using eval
    #TODO - pull this out into a shared resource
    #https://stackoverflow.com/questions/17529220/why-should-eval-be-avoided-in-bash-and-what-should-i-use-instead 
    red=`tput setaf 1`
    green=`tput setaf 2`
    reset=`tput sgr0`

    printf "Running eval: %s\n" "${1}"
    eval ${1}

    if [[ $? != 0 ]]; then
        printf "Command %sfailed%s!!\nExiting script...\n\n" "${red}" "${reset}"
        exit 1
    else
        printf "Command completed %ssuccessfully%s\n\n"   "${green}" "${reset}"
    fi
}

printf "Running DiskPrep using block_device=%s\n" "${block_device}"

#Mount root
myEval "cryptsetup open ${block_device}2 cryptroot"
myEval "mount /dev/mapper/cryptroot /mnt"

#Mount boot
myEval "mkdir -p /mnt/boot"
myEval "mount ${block_device}1 /mnt/boot"

#TODO update and verify /etc/pacman.d/mirrorlist

#Install the base packages
myEval "pacstrap /mnt base base-devel grub sudo wget vim"

#Generate an fstab file
myEval "genfstab -U /mnt >> /mnt/etc/fstab"

myEval "cp ./Chroot /mnt"
myEval "arch-chroot /mnt ./Chroot ${block_device}"
myEval "rm /mnt/Chroot"

#Unmount boot
myEval "umount /mnt/boot"
myEval "rmdir /mnt/boot"

#Unmount root
myEval "umount /mnt"
myEval "cryptsetup close cryptroot"

printf "BaseInstall finished...\n\n\n"