#!/bin/bash

block_device="${1}"

# Install grub as the bootloader
grub-install --target=i386-pc --recheck "${block_device}"

#Get root partition UUID (Do NOT use the UUID of the unlocked luks device)
block_device_uuid=$(blkid ${block_device}2 | sed -n 's/.* UUID=\"\([^\"]*\)\".*/\1/p')

#Set kernel parameters for unlocking encrypted root partition
sed -i "/GRUB_CMDLINE_LINUX=/c\\GRUB_CMDLINE_LINUX=\"rd.luks.uuid=${block_device_uuid} rd.luks.name=${block_device_uuid}=cryptroot root=/dev/mapper/cryptroot rd.luks.crypttab=no\"" /etc/default/grub

#Re-generate the grub.cfg file
grub-mkconfig -o /boot/grub/grub.cfg

echo en_US.UTF-8 UTF-8 > /etc/locale.gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
locale-gen

#Specify hooks
sed -i 's/^HOOKS.*/HOOKS=(base systemd autodetect keyboard modconf block sd-encrypt filesystems fsck)/' /etc/mkinitcpio.conf

#Create a new initramfs
mkinitcpio -p linux

printf "Setting password for root... \n"
passwd

#Give wheel group root privilege
echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/default
visudo -cf /etc/sudoers.d/default
if [ ! $? -eq 0 ]; then
    printf "\n\nError setting up local sudoers file\n\n" 
    exit 1
fi
printf "Successfully setup local sudoers file\n"

#Create a new user
read -p "Enter a username for a new ADMIN user: " -r new_user

useradd -m -G wheel -s /bin/bash "${new_user}"
passwd "${new_user}"

#Install utils
pacman -S --noconfirm firefox

#Install sway and it's dependencies
pacman -S --noconfirm sway dmenu ffmpeg i3status imagemagick rxvt-unicode asciidoc cmake
#Temp until dot files are under source control
comm1='mkdir -p ~/.config/sway'
comm2='cp /etc/sway/config ~/.config/sway'
comm3='echo "#:::::i3_ gaps:::::::::::::: " >> ~/.config/sway/config'
comm4='echo "gaps inner 10" >> ~/.config/sway/config'
comm5='echo "gaps outer 5" >> ~/.config/sway/config'
comm6='echo "smart_gaps on" >> ~/.config/sway/config'
su "${new_user}" -c "${comm1};${comm2};${comm3};${comm4};${comm5};${comm6}" 

printf "BaseInstall finished...\n\n\n"

#Exit arch-chroot
exit