#!/bin/bash

#Verify root privilege
if [[ "${EUID}" > 0 ]];then 
    printf "Requires root privileges. Please run under the root user\n"
    exit 1
fi

#TODO - Verify BIOS boot mode

#Determine block device to use
read -p "Enter the block device you want to use: " -r block_device
printf "\n"
if [[ ! -b "${block_device}" ]];then
    printf "Block device does not exist\nExiting script\n\n"
    exit 1
fi

#Partition/Encrypt/Format
./DiskPrep "${block_device}"

#Install the base system
./BaseInstall "${block_device}"